{
    "repository": "digitalocean/gta",
    "clone_url": "https://github.com/digitalocean/gta.git",
    "timestamp": "2023-05-30T11:35:41.928012Z",
    "clone_success": true,
    "number of actions": 2,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[test/test] \ud83d\ude80  Start image=crawlergpt:latest\n[test/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[test/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[test/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[test/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/c66e4e10-fed3-11ed-a890-af2cc187fc11/digitalocean-gta] user=0 workdir=\n[test/test]   \u2601  git clone 'https://github.com/actions/setup-go' # ref=v2\n[test/test] \ud83e\uddea  Matrix: map[go:1.19]\n[test/test] \u2b50 Run Main setup Go\n[test/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-go@v2/ dst=/var/run/act/actions/actions-setup-go@v2/\n[test/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-go@v2/] user=0 workdir=\n[test/test]   | OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown\r\n[test/test]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-go@v2/dist/index.js] user= workdir=\n[test/test]   \u274c  Failure - Main setup Go\n[test/test] Error response from daemon: Could not find the file /var/run/act/workflow/pathcmd.txt in container 43dc02ae1b637d91620b39443c2d262ba05254050d6ba673a42da3ab6c1b0ded\n[test/test] failed to remove container: Error response from daemon: No such container: 43dc02ae1b637d91620b39443c2d262ba05254050d6ba673a42da3ab6c1b0ded\n[test/test] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: Error response from daemon: remove act-test-test-24f46b2e65c2fc9b49cf0e305f210649cb0a45d5b5dc0a1380eb443748b7420b-env: volume is in use - [071c1f3aaeafee7af1e6a3cbdee05038209fce739437d56a12efe5c5bc1420c7] (original error: <nil>) (original error: <nil>)\n"
}