{
    "repository": "justdjango/django_chat",
    "stars": 67,
    "language": "python",
    "size": 1708,
    "clone_url": "https://github.com/justdjango/django_chat.git",
    "timestamp": "2023-06-28T18:08:51.083662Z",
    "clone_success": true,
    "number_of_actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_build_tools": [
        "pytest"
    ],
    "actions_test_build_tools": [
        "pytest"
    ],
    "actions_run": {
        "failed": true,
        "tests": [],
        "stdout": "[c210e67d-e64f-454f-8e80-d644881e11fb/linter] \ud83d\ude80  Start image=crawlergpt:latest\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest] \ud83d\ude80  Start image=crawlergpt:latest\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat] user=0 workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat] user=0 workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v3\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest] \u2b50 Run Main Checkout Code Repository\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \u2705  Success - Main Checkout Code Repository\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest] \u2b50 Run Main Build the Stack\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | [31] Failed to execute script docker-compose\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | Traceback (most recent call last):\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/connectionpool.py\", line 677, in urlopen\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/connectionpool.py\", line 392, in _make_request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1277, in request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1323, in _send_request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1272, in endheaders\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1032, in _send_output\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 972, in send\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/transport/unixconn.py\", line 43, in connect\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | PermissionError: [Errno 13] Permission denied\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | \n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | During handling of the above exception, another exception occurred:\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | \n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | Traceback (most recent call last):\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"requests/adapters.py\", line 449, in send\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/connectionpool.py\", line 727, in urlopen\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/util/retry.py\", line 410, in increment\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/packages/six.py\", line 734, in reraise\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/connectionpool.py\", line 677, in urlopen\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"urllib3/connectionpool.py\", line 392, in _make_request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1277, in request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1323, in _send_request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1272, in endheaders\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 1032, in _send_output\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"http/client.py\", line 972, in send\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/transport/unixconn.py\", line 43, in connect\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | \n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | During handling of the above exception, another exception occurred:\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | \n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | Traceback (most recent call last):\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/api/client.py\", line 214, in _retrieve_server_version\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/api/daemon.py\", line 181, in version\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/utils/decorators.py\", line 46, in inner\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/api/client.py\", line 237, in _get\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"requests/sessions.py\", line 543, in get\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"requests/sessions.py\", line 530, in request\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"requests/sessions.py\", line 643, in send\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"requests/adapters.py\", line 498, in send\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | \n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | During handling of the above exception, another exception occurred:\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | \n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | Traceback (most recent call last):\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker-compose\", line 3, in <module>\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"compose/cli/main.py\", line 81, in main\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"compose/cli/main.py\", line 200, in perform_command\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"compose/cli/command.py\", line 70, in project_from_options\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"compose/cli/command.py\", line 153, in get_project\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"compose/cli/docker_client.py\", line 43, in get_client\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"compose/cli/docker_client.py\", line 170, in docker_client\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/api/client.py\", line 197, in __init__\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   |   File \"docker/api/client.py\", line 222, in _retrieve_server_version\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   | docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest]   \u274c  Failure - Main Build the Stack\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest] exitcode '255': failure\n[c210e67d-e64f-454f-8e80-d644881e11fb/pytest] \ud83c\udfc1  Job failed\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2601  git clone 'https://github.com/pre-commit/action' # ref=v2.0.3\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter] \u2b50 Run Main Checkout Code Repository\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2705  Success - Main Checkout Code Repository\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter] \u2b50 Run Main Set up Python\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker cp src=/tmp/act-cache/8152bbb1-cd39-4245-ac5f-cd110d0d0ab7/act/actions-setup-python@v3/ dst=/var/run/act/actions/actions-setup-python@v3/\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/actions-setup-python@v3/] user=0 workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v3/dist/setup/index.js] user= workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Semantic version spec of 3.9 is 3.9\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: \n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? false\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? true\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? true\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? true\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? true\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? true\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::explicit? true\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::evaluating 6 versions\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::matched: 3.9.6\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.9.6/x64\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Found tool in cache Python 3.9.6 x64\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Successfully setup CPython (3.9.6)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::followSymbolicLinks 'true'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::followSymbolicLinks 'true'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::implicitDescendants 'true'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::matchDirectories 'true'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::omitBrokenSymbolicLinks 'true'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Search path '/tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat/requirements/base.txt'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Search path '/tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat/requirements/local.txt'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::/tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat/requirements/base.txt\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::/tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat/requirements/local.txt\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Found 2 files to hash.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [command]/opt/hostedtoolcache/Python/3.9.6/x64/bin/pip cache dir\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | /home/runneradmin/.cache/pip\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::global cache directory path is /home/runneradmin/.cache/pip\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Resolved Keys:\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::[\"setup-python-Linux-python-3.9.6-pip-0169dd00427d1abcb6b58dba4a289c22ee87838387389b92c06df6a2cb7c27d8\",\"setup-python-Linux-python-3.9.6-pip\"]\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Checking zstd --version\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::*** zstd command line interface 64-bits v1.5.0, by Yann Collet ***\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:34231/_apis/artifactcache/cache?keys=setup-python-Linux-python-3.9.6-pip-0169dd00427d1abcb6b58dba4a289c22ee87838387389b92c06df6a2cb7c27d8%252Csetup-python-Linux-python-3.9.6-pip&version=79a244514713d0ea96d5d8aab70186082a897848df6e845ec8308965d2f82f4f\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | pip cache is not found\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2753 add-matcher /run/act/actions/actions-setup-python@v3/.github/python.json\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2705  Success - Main Set up Python\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.9.6/x64\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.9.6/x64/lib\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2699  ::set-output:: python-version=3.9.6\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2699  ::set-output:: cache-hit=false\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.9.6/x64\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.9.6/x64/bin\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter] \u2b50 Run Main Run pre-commit\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker cp src=/tmp/act-cache/8152bbb1-cd39-4245-ac5f-cd110d0d0ab7/act/pre-commit-action@v2.0.3/ dst=/var/run/act/actions/pre-commit-action@v2.0.3/\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/pre-commit-action@v2.0.3/] user=0 workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/pre-commit-action@v2.0.3/dist/index.js] user= workdir=\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2753  ::group::install pre-commit\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [command]/opt/hostedtoolcache/Python/3.9.6/x64/bin/pip install pre-commit\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting pre-commit\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading pre_commit-3.3.3-py2.py3-none-any.whl (202 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting pyyaml>=5.1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting cfgv>=2.0.0\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting identify>=1.0.0\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading identify-2.5.24-py2.py3-none-any.whl (98 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting virtualenv>=20.10.0\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading virtualenv-20.23.1-py3-none-any.whl (3.3 MB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting nodeenv>=0.11.1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading nodeenv-1.8.0-py2.py3-none-any.whl (22 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages (from nodeenv>=0.11.1->pre-commit) (56.0.0)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting distlib<1,>=0.3.6\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting platformdirs<4,>=3.5.1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading platformdirs-3.8.0-py3-none-any.whl (16 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Collecting filelock<4,>=3.12\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |   Downloading filelock-3.12.2-py3-none-any.whl (10 kB)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Installing collected packages: platformdirs, filelock, distlib, virtualenv, pyyaml, nodeenv, identify, cfgv, pre-commit\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Successfully installed cfgv-3.3.1 distlib-0.3.6 filelock-3.12.2 identify-2.5.24 nodeenv-1.8.0 platformdirs-3.8.0 pre-commit-3.3.3 pyyaml-6.0 virtualenv-20.23.1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | You should consider upgrading via the '/opt/hostedtoolcache/Python/3.9.6/x64/bin/python -m pip install --upgrade pip' command.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [command]/opt/hostedtoolcache/Python/3.9.6/x64/bin/pip freeze --local\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | cfgv==3.3.1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | distlib==0.3.6\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | filelock==3.12.2\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | identify==2.5.24\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | nodeenv==1.8.0\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | platformdirs==3.8.0\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | pre-commit==3.3.3\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | PyYAML==6.0\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | virtualenv==20.23.1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2753  ::endgroup::\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Resolved Keys:\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::[\"pre-commit-2-943bb84bf3ff65aff039ffbbe5675ec3fa4a7a32fcbf4a9fce142dec4f574eb2-0c58d923a89e746d74b14cc2c8e4573ca5153ec087f2844645f29dc6a365e433\"]\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Checking zstd --version\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::*** zstd command line interface 64-bits v1.5.0, by Yann Collet ***\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:34231/_apis/artifactcache/cache?keys=pre-commit-2-943bb84bf3ff65aff039ffbbe5675ec3fa4a7a32fcbf4a9fce142dec4f574eb2-0c58d923a89e746d74b14cc2c8e4573ca5153ec087f2844645f29dc6a365e433&version=daaad88d35438f18ef22c9dee9688325e163e3ec248b8f04a97ec7dfe102a0ab\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [command]/opt/hostedtoolcache/Python/3.9.6/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Initializing environment for https://github.com/pre-commit/pre-commit-hooks.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Initializing environment for https://github.com/asottile/pyupgrade.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Initializing environment for https://github.com/psf/black.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Initializing environment for https://github.com/PyCQA/isort.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Initializing environment for https://github.com/PyCQA/flake8.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Initializing environment for https://github.com/PyCQA/flake8:flake8-isort.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Installing environment for https://github.com/pre-commit/pre-commit-hooks.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Once installed this environment will be reused.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m This may take a few minutes...\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Installing environment for https://github.com/asottile/pyupgrade.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Once installed this environment will be reused.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m This may take a few minutes...\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Installing environment for https://github.com/psf/black.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Once installed this environment will be reused.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m This may take a few minutes...\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Installing environment for https://github.com/PyCQA/isort.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m Once installed this environment will be reused.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | [INFO]\u001b[m This may take a few minutes...\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | An unexpected error has occurred: CalledProcessError: command: ('/home/runneradmin/.cache/pre-commit/repov6980rj8/py_env-python3/bin/python', '-mpip', 'install', '.')\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | return code: 1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | stdout:\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     Processing /home/runneradmin/.cache/pre-commit/repov6980rj8\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       Installing build dependencies: started\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       Installing build dependencies: finished with status 'done'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       Getting requirements to build wheel: started\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       Getting requirements to build wheel: finished with status 'done'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       Preparing metadata (pyproject.toml): started\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       Preparing metadata (pyproject.toml): finished with status 'error'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | stderr:\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       error: subprocess-exited-with-error\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       \n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       \u00d7 Preparing metadata (pyproject.toml) did not run successfully.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       \u2502 exit code: 1\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       \u2570\u2500> [14 lines of output]\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |           Traceback (most recent call last):\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |             File \"/home/runneradmin/.cache/pre-commit/repov6980rj8/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |               main()\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |             File \"/home/runneradmin/.cache/pre-commit/repov6980rj8/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |               json_out['return_val'] = hook(**hook_input['kwargs'])\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |             File \"/home/runneradmin/.cache/pre-commit/repov6980rj8/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 149, in prepare_metadata_for_build_wheel\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |               return hook(metadata_directory, config_settings)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |             File \"/tmp/pip-build-env-2cylr4jb/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py\", line 41, in prepare_metadata_for_build_wheel\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |               poetry = Factory().create_poetry(Path(\".\").resolve(), with_groups=False)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |             File \"/tmp/pip-build-env-2cylr4jb/overlay/lib/python3.9/site-packages/poetry/core/factory.py\", line 58, in create_poetry\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |               raise RuntimeError(\"The Poetry configuration is invalid:\\n\" + message)\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |           RuntimeError: The Poetry configuration is invalid:\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |             - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |           \n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |           [end of output]\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       \n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |       note: This error originates from a subprocess, and is likely not a problem with pip.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     error: metadata-generation-failed\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     \n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     \u00d7 Encountered error while generating package metadata.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     \u2570\u2500> See above for output.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     \n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     note: This is an issue with the package mentioned above, not pip.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   |     hint: See above for details.\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   | Check the log at /home/runneradmin/.cache/pre-commit/pre-commit.log\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u2757  ::error::The process '/opt/hostedtoolcache/Python/3.9.6/x64/bin/pre-commit' failed with exit code 3\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter]   \u274c  Failure - Main Run pre-commit\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter] exitcode '1': failure\n[c210e67d-e64f-454f-8e80-d644881e11fb/linter] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'linter' failed\n",
        "workflow": "/tmp/ad9c0f7e-1596-11ee-8a50-bb14de238602/justdjango-django_chat/.github/workflows/ci-crawler.yml",
        "build_tool": "pytest",
        "elapsed_time": 396.20155143737793
    }
}