{
    "repository": "ungarj/mapchete",
    "stars": 177,
    "language": "python",
    "size": 10542,
    "clone_url": "https://github.com/ungarj/mapchete.git",
    "timestamp": "2023-07-01T10:29:31.146020Z",
    "clone_success": true,
    "number_of_actions": 2,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_build_tools": [
        "pytest",
        "unknown"
    ],
    "actions_test_build_tools": [
        "pytest"
    ],
    "actions_run": {
        "failed": true,
        "tests": [],
        "stdout": "[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \ud83d\ude80  Start image=crawlergpt:latest\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/ungarj-mapchete] user=0 workdir=\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \ud83e\uddea  Matrix: map[os:ubuntu-latest python-version:3.8]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \u2b50 Run Main actions/checkout@v2\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2705  Success - Main actions/checkout@v2\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \u2b50 Run Main Set up Python 3.8\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker cp src=/tmp/act-cache/132173b8-b28d-4a94-a51d-c8414f63e3a3/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::Semantic version spec of 3.8 is 3.8\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? false\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? true\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? true\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? true\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? true\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? true\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::explicit? true\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::evaluating 6 versions\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::matched: 3.8.11\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.8.11/x64\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udcac  ::debug::Found tool in cache Python 3.8.11 x64\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Successfully setup CPython (3.8.11)\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2753 add-matcher /run/act/actions/actions-setup-python@v2/.github/python.json\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2705  Success - Main Set up Python 3.8\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.8.11/x64\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.8.11/x64/lib\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2699  ::set-output:: python-version=3.8.11\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.8.11/x64\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.8.11/x64/bin\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \u2b50 Run Main Install dependencies\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:1 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3622 B]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Ign:2 https://dl.hhvm.com/ubuntu focal InRelease\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Hit:3 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Err:4 https://dl.hhvm.com/ubuntu focal Release\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 108.157.214.54 443]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:5 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal InRelease [23.8 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:6 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [3611 B]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:7 http://dl.google.com/linux/chrome/deb stable InRelease [1825 B]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Hit:8 http://archive.ubuntu.com/ubuntu focal InRelease\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:9 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:10 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ Packages [81.0 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:11 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:12 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [211 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:13 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Err:7 http://dl.google.com/linux/chrome/deb stable InRelease\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:14 https://packages.microsoft.com/ubuntu/20.04/prod focal/main all Packages [2521 B]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:15 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal/main amd64 Packages [66.5 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:16 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [28.5 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:17 http://security.ubuntu.com/ubuntu focal-security/multiverse i386 Packages [8141 B]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:18 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2856 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1366 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:20 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1066 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:21 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3336 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted i386 Packages [36.9 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:23 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [744 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:24 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2479 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:25 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [764 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:26 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [39.5 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:27 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2636 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:28 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Get:29 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Hit:30 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb focal InRelease\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Reading package lists...\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | E: The repository 'https://dl.hhvm.com/ubuntu focal Release' no longer has a Release file.\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u274c  Failure - Main Install dependencies\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] exitcode '100': failure\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \u2b50 Run Main Stop containers\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/7] user= workdir=\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | [1065] Failed to execute script docker-compose\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Traceback (most recent call last):\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/connectionpool.py\", line 677, in urlopen\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/connectionpool.py\", line 392, in _make_request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1277, in request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1323, in _send_request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1272, in endheaders\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1032, in _send_output\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 972, in send\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/transport/unixconn.py\", line 43, in connect\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | PermissionError: [Errno 13] Permission denied\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | During handling of the above exception, another exception occurred:\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Traceback (most recent call last):\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"requests/adapters.py\", line 449, in send\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/connectionpool.py\", line 727, in urlopen\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/util/retry.py\", line 410, in increment\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/packages/six.py\", line 734, in reraise\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/connectionpool.py\", line 677, in urlopen\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"urllib3/connectionpool.py\", line 392, in _make_request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1277, in request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1323, in _send_request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1272, in endheaders\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 1032, in _send_output\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"http/client.py\", line 972, in send\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/transport/unixconn.py\", line 43, in connect\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | During handling of the above exception, another exception occurred:\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Traceback (most recent call last):\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/api/client.py\", line 214, in _retrieve_server_version\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/api/daemon.py\", line 181, in version\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/utils/decorators.py\", line 46, in inner\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/api/client.py\", line 237, in _get\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"requests/sessions.py\", line 543, in get\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"requests/sessions.py\", line 530, in request\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"requests/sessions.py\", line 643, in send\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"requests/adapters.py\", line 498, in send\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | During handling of the above exception, another exception occurred:\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | \n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | Traceback (most recent call last):\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker-compose\", line 3, in <module>\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"compose/cli/main.py\", line 81, in main\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"compose/cli/main.py\", line 200, in perform_command\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"compose/cli/command.py\", line 70, in project_from_options\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"compose/cli/command.py\", line 153, in get_project\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"compose/cli/docker_client.py\", line 43, in get_client\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"compose/cli/docker_client.py\", line 170, in docker_client\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/api/client.py\", line 197, in __init__\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   |   File \"docker/api/client.py\", line 222, in _retrieve_server_version\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   | docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test]   \u274c  Failure - Main Stop containers\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] exitcode '255': failure\n[1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3/test] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'test' failed\n",
        "workflow": {
            "path": "/tmp/558156d8-17ed-11ee-8a50-bb14de238602/ungarj-mapchete/.github/workflows/python-package-crawler.yml",
            "type": "pytest"
        },
        "workflow_name": "1ac9f8b3-dd3f-4ad8-9607-883b7dea8dd3",
        "build_tool": "pytest",
        "elapsed_time": 121.04542303085327
    }
}