{
    "repository": "cms-dev/cms",
    "clone_url": "https://github.com/cms-dev/cms.git",
    "timestamp": "2023-05-29T14:16:41.668623Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[ci/test] \ud83d\ude80  Start image=crawlergpt:latest\n[ci/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[ci/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[ci/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[ci/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/cms-dev-cms] user=0 workdir=\n[ci/test]   \u2601  git clone 'https://github.com/codecov/codecov-action' # ref=v3\n[ci/test]   \u2601  git clone 'https://github.com/codecov/codecov-action' # ref=v3\n[ci/test] \u2b50 Run Main actions/checkout@v2\n[ci/test]   \u2705  Success - Main actions/checkout@v2\n[ci/test] \u2b50 Run Main Check available cgroups\n[ci/test]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=\n[ci/test]   | tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)\n[ci/test]   | cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,name=systemd)\n[ci/test]   | cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)\n[ci/test]   | cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)\n[ci/test]   | cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)\n[ci/test]   | cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)\n[ci/test]   | cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)\n[ci/test]   | cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)\n[ci/test]   | cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)\n[ci/test]   | cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)\n[ci/test]   | cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)\n[ci/test]   | cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)\n[ci/test]   | cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)\n[ci/test]   \u2705  Success - Main Check available cgroups\n[ci/test] \u2b50 Run Main Build docker image\n[ci/test]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[ci/test]   | [40] Failed to execute script docker-compose\n[ci/test]   | Traceback (most recent call last):\n[ci/test]   |   File \"urllib3/connectionpool.py\", line 677, in urlopen\n[ci/test]   |   File \"urllib3/connectionpool.py\", line 392, in _make_request\n[ci/test]   |   File \"http/client.py\", line 1277, in request\n[ci/test]   |   File \"http/client.py\", line 1323, in _send_request\n[ci/test]   |   File \"http/client.py\", line 1272, in endheaders\n[ci/test]   |   File \"http/client.py\", line 1032, in _send_output\n[ci/test]   |   File \"http/client.py\", line 972, in send\n[ci/test]   |   File \"docker/transport/unixconn.py\", line 43, in connect\n[ci/test]   | PermissionError: [Errno 13] Permission denied\n[ci/test]   | \n[ci/test]   | During handling of the above exception, another exception occurred:\n[ci/test]   | \n[ci/test]   | Traceback (most recent call last):\n[ci/test]   |   File \"requests/adapters.py\", line 449, in send\n[ci/test]   |   File \"urllib3/connectionpool.py\", line 727, in urlopen\n[ci/test]   |   File \"urllib3/util/retry.py\", line 410, in increment\n[ci/test]   |   File \"urllib3/packages/six.py\", line 734, in reraise\n[ci/test]   |   File \"urllib3/connectionpool.py\", line 677, in urlopen\n[ci/test]   |   File \"urllib3/connectionpool.py\", line 392, in _make_request\n[ci/test]   |   File \"http/client.py\", line 1277, in request\n[ci/test]   |   File \"http/client.py\", line 1323, in _send_request\n[ci/test]   |   File \"http/client.py\", line 1272, in endheaders\n[ci/test]   |   File \"http/client.py\", line 1032, in _send_output\n[ci/test]   |   File \"http/client.py\", line 972, in send\n[ci/test]   |   File \"docker/transport/unixconn.py\", line 43, in connect\n[ci/test]   | urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[ci/test]   | \n[ci/test]   | During handling of the above exception, another exception occurred:\n[ci/test]   | \n[ci/test]   | Traceback (most recent call last):\n[ci/test]   |   File \"docker/api/client.py\", line 214, in _retrieve_server_version\n[ci/test]   |   File \"docker/api/daemon.py\", line 181, in version\n[ci/test]   |   File \"docker/utils/decorators.py\", line 46, in inner\n[ci/test]   |   File \"docker/api/client.py\", line 237, in _get\n[ci/test]   |   File \"requests/sessions.py\", line 543, in get\n[ci/test]   |   File \"requests/sessions.py\", line 530, in request\n[ci/test]   |   File \"requests/sessions.py\", line 643, in send\n[ci/test]   |   File \"requests/adapters.py\", line 498, in send\n[ci/test]   | requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[ci/test]   | \n[ci/test]   | During handling of the above exception, another exception occurred:\n[ci/test]   | \n[ci/test]   | Traceback (most recent call last):\n[ci/test]   |   File \"docker-compose\", line 3, in <module>\n[ci/test]   |   File \"compose/cli/main.py\", line 81, in main\n[ci/test]   |   File \"compose/cli/main.py\", line 200, in perform_command\n[ci/test]   |   File \"compose/cli/command.py\", line 70, in project_from_options\n[ci/test]   |   File \"compose/cli/command.py\", line 153, in get_project\n[ci/test]   |   File \"compose/cli/docker_client.py\", line 43, in get_client\n[ci/test]   |   File \"compose/cli/docker_client.py\", line 170, in docker_client\n[ci/test]   |   File \"docker/api/client.py\", line 197, in __init__\n[ci/test]   |   File \"docker/api/client.py\", line 222, in _retrieve_server_version\n[ci/test]   | docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))\n[ci/test]   \u274c  Failure - Main Build docker image\n[ci/test] exitcode '255': failure\n[ci/test] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Job 'test' failed\n"
}