{
    "repository": "etianen/django-watson",
    "clone_url": "https://github.com/etianen/django-watson.git",
    "timestamp": "2023-05-29T14:14:00.531486Z",
    "clone_success": true,
    "number of actions": 2,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Django CI/build] \ud83d\ude80  Start image=crawlergpt:latest\n[Django CI/build]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Django CI/build]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Django CI/build]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/etianen-django-watson] user=0 workdir=\n[Django CI/build]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[Django CI/build] \ud83e\uddea  Matrix: map[django-version:3.2 python-version:3.7]\n[Django CI/build] \u2b50 Run Main actions/checkout@v2\n[Django CI/build]   \u2705  Success - Main actions/checkout@v2\n[Django CI/build] \u2b50 Run Main Set up Python 3.7\n[Django CI/build]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[Django CI/build]   \ud83d\udcac  ::debug::Semantic version spec of 3.7 is 3.7\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: \n[Django CI/build]   \ud83d\udcac  ::debug::explicit? false\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[Django CI/build]   \ud83d\udcac  ::debug::explicit? true\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[Django CI/build]   \ud83d\udcac  ::debug::explicit? true\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[Django CI/build]   \ud83d\udcac  ::debug::explicit? true\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[Django CI/build]   \ud83d\udcac  ::debug::explicit? true\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[Django CI/build]   \ud83d\udcac  ::debug::explicit? true\n[Django CI/build]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[Django CI/build]   \ud83d\udcac  ::debug::explicit? true\n[Django CI/build]   \ud83d\udcac  ::debug::evaluating 6 versions\n[Django CI/build]   \ud83d\udcac  ::debug::matched: 3.7.11\n[Django CI/build]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.7.11/x64\n[Django CI/build]   \ud83d\udcac  ::debug::Found tool in cache Python 3.7.11 x64\n[Django CI/build]   | Successfully setup CPython (3.7.11)\n[Django CI/build]   \u2753 add-matcher /run/act/actions/actions-setup-python@v2/.github/python.json\n[Django CI/build]   \u2705  Success - Main Set up Python 3.7\n[Django CI/build]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.7.11/x64\n[Django CI/build]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.7.11/x64/lib\n[Django CI/build]   \u2699  ::set-output:: python-version=3.7.11\n[Django CI/build]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64\n[Django CI/build]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64/bin\n[Django CI/build] \u2b50 Run Main psycopg2 prerequisites\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[Django CI/build]   | Reading package lists...\n[Django CI/build]   | Building dependency tree...\n[Django CI/build]   | Reading state information...\n[Django CI/build]   | libpq-dev is already the newest version (13.4-1.pgdg20.04+1).\n[Django CI/build]   | 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.\n[Django CI/build]   \u2705  Success - Main psycopg2 prerequisites\n[Django CI/build] \u2b50 Run Main Install Dependencies\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=\n[Django CI/build]   | Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (21.2.4)\n[Django CI/build]   | Collecting pip\n[Django CI/build]   |   Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)\n[Django CI/build]   | Installing collected packages: pip\n[Django CI/build]   |   Attempting uninstall: pip\n[Django CI/build]   |     Found existing installation: pip 21.2.4\n[Django CI/build]   |     Uninstalling pip-21.2.4:\n[Django CI/build]   |       Successfully uninstalled pip-21.2.4\n[Django CI/build]   | Successfully installed pip-23.1.2\n[Django CI/build]   | Obtaining file:///tmp/de65f406-fe28-11ed-a890-af2cc187fc11/etianen-django-watson\n[Django CI/build]   |   Installing build dependencies: started\n[Django CI/build]   |   Installing build dependencies: finished with status 'done'\n[Django CI/build]   |   Checking if build backend supports build_editable: started\n[Django CI/build]   |   Checking if build backend supports build_editable: finished with status 'done'\n[Django CI/build]   |   Getting requirements to build editable: started\n[Django CI/build]   |   Getting requirements to build editable: finished with status 'done'\n[Django CI/build]   |   Preparing editable metadata (pyproject.toml): started\n[Django CI/build]   |   Preparing editable metadata (pyproject.toml): finished with status 'done'\n[Django CI/build]   | Collecting flake8\n[Django CI/build]   |   Downloading flake8-5.0.4-py2.py3-none-any.whl (61 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 61.9/61.9 kB 3.1 MB/s eta 0:00:00\n[Django CI/build]   | Collecting coverage\n[Django CI/build]   |   Downloading coverage-7.2.6-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (225 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 225.5/225.5 kB 11.6 MB/s eta 0:00:00\n[Django CI/build]   | Collecting Django~=3.2.0\n[Django CI/build]   |   Downloading Django-3.2.19-py3-none-any.whl (7.9 MB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 7.9/7.9 MB 38.5 MB/s eta 0:00:00\n[Django CI/build]   | Collecting psycopg2==2.8.6\n[Django CI/build]   |   Downloading psycopg2-2.8.6.tar.gz (383 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 383.8/383.8 kB 27.0 MB/s eta 0:00:00\n[Django CI/build]   |   Installing build dependencies: started\n[Django CI/build]   |   Installing build dependencies: finished with status 'done'\n[Django CI/build]   |   Getting requirements to build wheel: started\n[Django CI/build]   |   Getting requirements to build wheel: finished with status 'done'\n[Django CI/build]   |   Preparing metadata (pyproject.toml): started\n[Django CI/build]   |   Preparing metadata (pyproject.toml): finished with status 'done'\n[Django CI/build]   | Collecting mysqlclient\n[Django CI/build]   |   Downloading mysqlclient-2.1.1.tar.gz (88 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 88.1/88.1 kB 5.0 MB/s eta 0:00:00\n[Django CI/build]   |   Installing build dependencies: started\n[Django CI/build]   |   Installing build dependencies: finished with status 'done'\n[Django CI/build]   |   Getting requirements to build wheel: started\n[Django CI/build]   |   Getting requirements to build wheel: finished with status 'done'\n[Django CI/build]   |   Preparing metadata (pyproject.toml): started\n[Django CI/build]   |   Preparing metadata (pyproject.toml): finished with status 'done'\n[Django CI/build]   | Collecting mccabe<0.8.0,>=0.7.0 (from flake8)\n[Django CI/build]   |   Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)\n[Django CI/build]   | Collecting pycodestyle<2.10.0,>=2.9.0 (from flake8)\n[Django CI/build]   |   Downloading pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 41.5/41.5 kB 5.9 MB/s eta 0:00:00\n[Django CI/build]   | Collecting pyflakes<2.6.0,>=2.5.0 (from flake8)\n[Django CI/build]   |   Downloading pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 66.1/66.1 kB 3.1 MB/s eta 0:00:00\n[Django CI/build]   | Collecting importlib-metadata<4.3,>=1.1.0 (from flake8)\n[Django CI/build]   |   Downloading importlib_metadata-4.2.0-py3-none-any.whl (16 kB)\n[Django CI/build]   | Collecting asgiref<4,>=3.3.2 (from Django~=3.2.0)\n[Django CI/build]   |   Downloading asgiref-3.7.2-py3-none-any.whl (24 kB)\n[Django CI/build]   | Collecting pytz (from Django~=3.2.0)\n[Django CI/build]   |   Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 502.3/502.3 kB 11.3 MB/s eta 0:00:00\n[Django CI/build]   | Collecting sqlparse>=0.2.2 (from Django~=3.2.0)\n[Django CI/build]   |   Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)\n[Django CI/build]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 41.2/41.2 kB 1.8 MB/s eta 0:00:00\n[Django CI/build]   | Collecting typing-extensions>=4 (from asgiref<4,>=3.3.2->Django~=3.2.0)\n[Django CI/build]   |   Downloading typing_extensions-4.6.2-py3-none-any.whl (31 kB)\n[Django CI/build]   | Collecting zipp>=0.5 (from importlib-metadata<4.3,>=1.1.0->flake8)\n[Django CI/build]   |   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)\n[Django CI/build]   | Building wheels for collected packages: psycopg2, mysqlclient, django-watson\n[Django CI/build]   |   Building wheel for psycopg2 (pyproject.toml): started\n[Django CI/build]   |   Building wheel for psycopg2 (pyproject.toml): finished with status 'done'\n[Django CI/build]   |   Created wheel for psycopg2: filename=psycopg2-2.8.6-cp37-cp37m-linux_x86_64.whl size=509008 sha256=8404d20df9605319dce4acd694c46e755dd97f7ae2e455e7994bac45fcb2c440\n[Django CI/build]   |   Stored in directory: /home/runneradmin/.cache/pip/wheels/25/78/75/9c0323f7e1fb42143cbd2439302beb7850a1034abb961cb281\n[Django CI/build]   |   Building wheel for mysqlclient (pyproject.toml): started\n[Django CI/build]   |   Building wheel for mysqlclient (pyproject.toml): finished with status 'done'\n[Django CI/build]   |   Created wheel for mysqlclient: filename=mysqlclient-2.1.1-cp37-cp37m-linux_x86_64.whl size=109914 sha256=49ce4335bfa3576251c51a0db56c92c1890dffc18e944ca6ff8d0ddb2abab8e9\n[Django CI/build]   |   Stored in directory: /home/runneradmin/.cache/pip/wheels/95/2d/67/2cb3f82e435fc8e055cb2761a15a0812bf086068f6fb835462\n[Django CI/build]   |   Building editable for django-watson (pyproject.toml): started\n[Django CI/build]   |   Building editable for django-watson (pyproject.toml): finished with status 'done'\n[Django CI/build]   |   Created wheel for django-watson: filename=django_watson-1.6.3-0.editable-py2.py3-none-any.whl size=4708 sha256=005b85c50e66f0b931fe99c59fd51df0715a51037655573de56c1f54ce713156\n[Django CI/build]   |   Stored in directory: /tmp/pip-ephem-wheel-cache-7e43khgw/wheels/cb/eb/a8/aa1385f69366db7e6e63a1fa5d04387a59d11ae32a6030e8bf\n[Django CI/build]   | Successfully built psycopg2 mysqlclient django-watson\n[Django CI/build]   | Installing collected packages: pytz, django-watson, zipp, typing-extensions, sqlparse, pyflakes, pycodestyle, psycopg2, mysqlclient, mccabe, coverage, importlib-metadata, asgiref, flake8, Django\n[Django CI/build]   | Successfully installed Django-3.2.19 asgiref-3.7.2 coverage-7.2.6 django-watson-1.6.3 flake8-5.0.4 importlib-metadata-4.2.0 mccabe-0.7.0 mysqlclient-2.1.1 psycopg2-2.8.6 pycodestyle-2.9.1 pyflakes-2.5.0 pytz-2023.3 sqlparse-0.4.4 typing-extensions-4.6.2 zipp-3.15.0\n[Django CI/build]   | \n[Django CI/build]   | [notice] A new release of pip is available: 20.1.1 -> 23.1.2\n[Django CI/build]   | [notice] To update, run: pip install --upgrade pip\n[Django CI/build]   \u2705  Success - Main Install Dependencies\n[Django CI/build] \u2b50 Run Main Run Flake8\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=\n[Django CI/build]   \u2705  Success - Main Run Flake8\n[Django CI/build] \u2b50 Run Main Run Tests\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=\n[Django CI/build]   | Creating test database for alias 'default'...\n[Django CI/build]   | System check identified some issues:\n[Django CI/build]   | \n[Django CI/build]   | WARNINGS:\n[Django CI/build]   | ?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.\n[Django CI/build]   | ?: (urls.W005) URL namespace 'watson' isn't unique. You may not be able to reverse all URLs in this namespace\n[Django CI/build]   | test_watson.WatsonTestModel1: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.\n[Django CI/build]   | \tHINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.\n[Django CI/build]   | \n[Django CI/build]   | System check identified 3 issues (0 silenced).\n[Django CI/build]   | .....s..............................ss............./opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'watson.models.SearchEntry'> QuerySet.\n[Django CI/build]   |   allow_empty_first_page=allow_empty_first_page, **kwargs)\n[Django CI/build]   | ...\n[Django CI/build]   | ----------------------------------------------------------------------\n[Django CI/build]   | Ran 54 tests in 2.986s\n[Django CI/build]   | \n[Django CI/build]   | OK (skipped=3)\n[Django CI/build]   | Destroying test database for alias 'default'...\n[Django CI/build]   \u2705  Success - Main Run Tests\n[Django CI/build] \u2b50 Run Main Run Tests psql\n[Django CI/build]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/6] user= workdir=\n[Django CI/build]   | Creating test database for alias 'default'...\n[Django CI/build]   | /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py:310: RuntimeWarning: Normally Django will use a connection to the 'postgres' database to avoid running initialization queries against the production database when it's not needed (for example, when running tests). Django was unable to create a connection to the 'postgres' database and will use the first PostgreSQL database instead.\n[Django CI/build]   |   RuntimeWarning\n[Django CI/build]   | Traceback (most recent call last):\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 219, in ensure_connection\n[Django CI/build]   |     self.connect()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 200, in connect\n[Django CI/build]   |     self.connection = self.get_new_connection(conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 187, in get_new_connection\n[Django CI/build]   |     connection = Database.connect(**conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/psycopg2/__init__.py\", line 127, in connect\n[Django CI/build]   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n[Django CI/build]   | psycopg2.OperationalError: could not connect to server: Connection refused\n[Django CI/build]   | \tIs the server running on host \"127.0.0.1\" and accepting\n[Django CI/build]   | \tTCP/IP connections on port 5432?\n[Django CI/build]   | \n[Django CI/build]   | \n[Django CI/build]   | The above exception was the direct cause of the following exception:\n[Django CI/build]   | \n[Django CI/build]   | Traceback (most recent call last):\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 301, in _nodb_cursor\n[Django CI/build]   |     with super()._nodb_cursor() as cursor:\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/contextlib.py\", line 112, in __enter__\n[Django CI/build]   |     return next(self.gen)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 620, in _nodb_cursor\n[Django CI/build]   |     with conn.cursor() as cursor:\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 259, in cursor\n[Django CI/build]   |     return self._cursor()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 235, in _cursor\n[Django CI/build]   |     self.ensure_connection()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 219, in ensure_connection\n[Django CI/build]   |     self.connect()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/utils.py\", line 90, in __exit__\n[Django CI/build]   |     raise dj_exc_value.with_traceback(traceback) from exc_value\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 219, in ensure_connection\n[Django CI/build]   |     self.connect()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 200, in connect\n[Django CI/build]   |     self.connection = self.get_new_connection(conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 187, in get_new_connection\n[Django CI/build]   |     connection = Database.connect(**conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/psycopg2/__init__.py\", line 127, in connect\n[Django CI/build]   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n[Django CI/build]   | django.db.utils.OperationalError: could not connect to server: Connection refused\n[Django CI/build]   | \tIs the server running on host \"127.0.0.1\" and accepting\n[Django CI/build]   | \tTCP/IP connections on port 5432?\n[Django CI/build]   | \n[Django CI/build]   | \n[Django CI/build]   | During handling of the above exception, another exception occurred:\n[Django CI/build]   | \n[Django CI/build]   | Traceback (most recent call last):\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 219, in ensure_connection\n[Django CI/build]   |     self.connect()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 200, in connect\n[Django CI/build]   |     self.connection = self.get_new_connection(conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 187, in get_new_connection\n[Django CI/build]   |     connection = Database.connect(**conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/psycopg2/__init__.py\", line 127, in connect\n[Django CI/build]   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n[Django CI/build]   | psycopg2.OperationalError: could not connect to server: Connection refused\n[Django CI/build]   | \tIs the server running on host \"127.0.0.1\" and accepting\n[Django CI/build]   | \tTCP/IP connections on port 5432?\n[Django CI/build]   | \n[Django CI/build]   | \n[Django CI/build]   | The above exception was the direct cause of the following exception:\n[Django CI/build]   | \n[Django CI/build]   | Traceback (most recent call last):\n[Django CI/build]   |   File \"tests/runtests.py\", line 144, in <module>\n[Django CI/build]   |     main()\n[Django CI/build]   |   File \"tests/runtests.py\", line 138, in main\n[Django CI/build]   |     failures = test_runner.run_tests([\"test_watson\"])\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/test/runner.py\", line 725, in run_tests\n[Django CI/build]   |     old_config = self.setup_databases(aliases=databases)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/test/runner.py\", line 645, in setup_databases\n[Django CI/build]   |     debug_sql=self.debug_sql, parallel=self.parallel, **kwargs\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/test/utils.py\", line 183, in setup_databases\n[Django CI/build]   |     serialize=connection.settings_dict['TEST'].get('SERIALIZE', True),\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/creation.py\", line 57, in create_test_db\n[Django CI/build]   |     self._create_test_db(verbosity, autoclobber, keepdb)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/creation.py\", line 191, in _create_test_db\n[Django CI/build]   |     with self._nodb_cursor() as cursor:\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/contextlib.py\", line 112, in __enter__\n[Django CI/build]   |     return next(self.gen)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 319, in _nodb_cursor\n[Django CI/build]   |     with conn.cursor() as cursor:\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 259, in cursor\n[Django CI/build]   |     return self._cursor()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 235, in _cursor\n[Django CI/build]   |     self.ensure_connection()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 219, in ensure_connection\n[Django CI/build]   |     self.connect()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/utils.py\", line 90, in __exit__\n[Django CI/build]   |     raise dj_exc_value.with_traceback(traceback) from exc_value\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 219, in ensure_connection\n[Django CI/build]   |     self.connect()\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 200, in connect\n[Django CI/build]   |     self.connection = self.get_new_connection(conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/utils/asyncio.py\", line 33, in inner\n[Django CI/build]   |     return func(*args, **kwargs)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 187, in get_new_connection\n[Django CI/build]   |     connection = Database.connect(**conn_params)\n[Django CI/build]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/psycopg2/__init__.py\", line 127, in connect\n[Django CI/build]   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n[Django CI/build]   | django.db.utils.OperationalError: could not connect to server: Connection refused\n[Django CI/build]   | \tIs the server running on host \"127.0.0.1\" and accepting\n[Django CI/build]   | \tTCP/IP connections on port 5432?\n[Django CI/build]   | \n[Django CI/build]   \u274c  Failure - Main Run Tests psql\n[Django CI/build] exitcode '1': failure\n[Django CI/build] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Job 'build' failed\n"
}