{
    "repository": "py-mine/PyMine-Server",
    "clone_url": "https://github.com/py-mine/PyMine-Server.git",
    "timestamp": "2023-05-29T16:03:47.902126Z",
    "clone_success": true,
    "number of actions": 4,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[PyTest/pytest] \ud83d\ude80  Start image=crawlergpt:latest\n[PyTest/pytest]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[PyTest/pytest]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[PyTest/pytest]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[PyTest/pytest]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/py-mine-PyMine-Server] user=0 workdir=\n[PyTest/pytest]   \u2601  git clone 'https://github.com/actions/cache' # ref=v2\n[PyTest/pytest] Unable to checkout 8492260343ad570701412c2f464a5877dc76bace: EOF\n[PyTest/pytest] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": "Error: EOF\n"
}