{
    "repository": "ricobl/django-thumbor",
    "clone_url": "https://github.com/ricobl/django-thumbor.git",
    "timestamp": "2023-05-29T14:40:34.106509Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Run tests/test] \ud83d\ude80  Start image=crawlergpt:latest\n[Run tests/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Run tests/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run tests/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run tests/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/ricobl-django-thumbor] user=0 workdir=\n[Run tests/test]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[Run tests/test]   \u2601  git clone 'https://github.com/VaultVulp/action-pipenv' # ref=v2.0.1\n[Run tests/test]   \u2601  git clone 'https://github.com/VaultVulp/action-pipenv' # ref=v2.0.1\n[Run tests/test] \ud83e\uddea  Matrix: map[django-version:3.2 python-version:3.9]\n[Run tests/test] \u2b50 Run Main Checkout repo\n[Run tests/test]   \u2705  Success - Main Checkout repo\n[Run tests/test] \u2b50 Run Main Set Up Python 3.9\n[Run tests/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[Run tests/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[Run tests/test]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[Run tests/test]   \ud83d\udcac  ::debug::Semantic version spec of 3.9 is 3.9\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: \n[Run tests/test]   \ud83d\udcac  ::debug::explicit? false\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[Run tests/test]   \ud83d\udcac  ::debug::explicit? true\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[Run tests/test]   \ud83d\udcac  ::debug::explicit? true\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[Run tests/test]   \ud83d\udcac  ::debug::explicit? true\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[Run tests/test]   \ud83d\udcac  ::debug::explicit? true\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[Run tests/test]   \ud83d\udcac  ::debug::explicit? true\n[Run tests/test]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[Run tests/test]   \ud83d\udcac  ::debug::explicit? true\n[Run tests/test]   \ud83d\udcac  ::debug::evaluating 6 versions\n[Run tests/test]   \ud83d\udcac  ::debug::matched: 3.9.6\n[Run tests/test]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.9.6/x64\n[Run tests/test]   \ud83d\udcac  ::debug::Found tool in cache Python 3.9.6 x64\n[Run tests/test]   | Successfully setup CPython (3.9.6)\n[Run tests/test]   \u2753 add-matcher /run/act/actions/actions-setup-python@v2/.github/python.json\n[Run tests/test]   \u2705  Success - Main Set Up Python 3.9\n[Run tests/test]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.9.6/x64\n[Run tests/test]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.9.6/x64/lib\n[Run tests/test]   \u2699  ::set-output:: python-version=3.9.6\n[Run tests/test]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.9.6/x64\n[Run tests/test]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.9.6/x64/bin\n[Run tests/test] \u2b50 Run Main Display Python version\n[Run tests/test]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[Run tests/test]   | 3.9.6 (default, Jun 28 2021, 19:59:42) \n[Run tests/test]   | [GCC 9.3.0]\n[Run tests/test]   \u2705  Success - Main Display Python version\n[Run tests/test] \u2b50 Run Main Install dependecies\n[Run tests/test]   \ud83d\udc33  docker build -t act-vaultvulp-action-pipenv-v2-0-1-dockeraction:latest /home/andre-silva/.cache/act/VaultVulp-action-pipenv@v2.0.1/\n[Run tests/test]   \ud83d\udc33  docker pull image=act-vaultvulp-action-pipenv-v2-0-1-dockeraction:latest platform= username= forcePull=false\n[Run tests/test]   \ud83d\udc33  docker create image=act-vaultvulp-action-pipenv-v2-0-1-dockeraction:latest platform= entrypoint=[] cmd=[\"install --dev\"]\n[Run tests/test]   \ud83d\udc33  docker run image=act-vaultvulp-action-pipenv-v2-0-1-dockeraction:latest platform= entrypoint=[] cmd=[\"install --dev\"]\n[Run tests/test]   | Traceback (most recent call last):\n[Run tests/test]   |   File \"/usr/local/bin/pipenv\", line 8, in <module>\n[Run tests/test]   |     sys.exit(cli())\n[Run tests/test]   |              ^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py\", line 1130, in __call__\n[Run tests/test]   |     return self.main(*args, **kwargs)\n[Run tests/test]   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/cli/options.py\", line 58, in main\n[Run tests/test]   |     return super().main(*args, **kwargs, windows_expand_args=False)\n[Run tests/test]   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py\", line 1055, in main\n[Run tests/test]   |     rv = self.invoke(ctx)\n[Run tests/test]   |          ^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py\", line 1657, in invoke\n[Run tests/test]   |     return _process_result(sub_ctx.command.invoke(sub_ctx))\n[Run tests/test]   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py\", line 1404, in invoke\n[Run tests/test]   |     return ctx.invoke(self.callback, **ctx.params)\n[Run tests/test]   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py\", line 760, in invoke\n[Run tests/test]   |     return __callback(*args, **kwargs)\n[Run tests/test]   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py\", line 84, in new_func\n[Run tests/test]   |     return ctx.invoke(f, obj, *args, **kwargs)\n[Run tests/test]   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py\", line 760, in invoke\n[Run tests/test]   |     return __callback(*args, **kwargs)\n[Run tests/test]   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/cli/command.py\", line 235, in install\n[Run tests/test]   |     do_install(\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/routines/install.py\", line 69, in do_install\n[Run tests/test]   |     ensure_project(\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/utils/project.py\", line 24, in ensure_project\n[Run tests/test]   |     if project.s.PIPENV_USE_SYSTEM or project.virtualenv_exists:\n[Run tests/test]   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/project.py\", line 250, in virtualenv_exists\n[Run tests/test]   |     if os.path.exists(self.virtualenv_location):\n[Run tests/test]   |                       ^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/project.py\", line 447, in virtualenv_location\n[Run tests/test]   |     self._virtualenv_location = self.get_location_for_virtualenv()\n[Run tests/test]   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/project.py\", line 272, in get_location_for_virtualenv\n[Run tests/test]   |     return str(get_workon_home().joinpath(self.virtualenv_name))\n[Run tests/test]   |                ^^^^^^^^^^^^^^^^^\n[Run tests/test]   |   File \"/usr/local/lib/python3.11/site-packages/pipenv/utils/shell.py\", line 195, in get_workon_home\n[Run tests/test]   |     os.makedirs(expanded_path, exist_ok=True)\n[Run tests/test]   |   File \"<frozen os>\", line 215, in makedirs\n[Run tests/test]   |   File \"<frozen os>\", line 215, in makedirs\n[Run tests/test]   |   File \"<frozen os>\", line 225, in makedirs\n[Run tests/test]   | PermissionError: [Errno 13] Permission denied: '/.local'\n[Run tests/test]   \u274c  Failure - Main Install dependecies\n[Run tests/test] exit with `FAILURE`: 1\n[Run tests/test] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Job 'test' failed\n"
}